
pull_request_rules:
  # rebase+merge strategy
  - name: Put pull requests in the rebase+merge queue + Put pull requests in the squash+merge
      queue
    conditions: []
    actions:
      queue:
queue_rules:
  - name: duplicated default from Put pull requests in the squash+merge queue
    queue_conditions:
      - label=merge me
      - 'check-success=Frontend_tests'
      - 'check-success~=.*Backend_tests.*'
      - label=squash+merge me
      - 'check-success=Frontend_tests'
      - 'check-success=Backend_tests'
    merge_conditions: []
    update_method: merge
    merge_method: squash
  - name: default
    queue_conditions:
      - label=merge me
      - 'check-success=Frontend_tests'
      - 'check-success~=.*Backend_tests.*'
    merge_conditions: []
    update_method: rebase
    merge_method: merge
