FROM haskell:9.10.3 AS build

RUN apt-get update && apt-get install -y --no-install-recommends protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*
ADD https://github.com/well-typed/eventlog-live/archive/0c991bb18af21dccd2035fa8a955741069cbb203.tar.gz /src.tar.gz
RUN mkdir /src && tar -xzf /src.tar.gz -C /src --strip-components=1 && \
    cd /src && cabal update && \
    cabal install exe:eventlog-live-otelcol --installdir=/out --install-method=copy
FROM debian:bookworm-slim
COPY --from=build /out/eventlog-live-otelcol /usr/local/bin/eventlog-live-otelcol

RUN mkdir -p -m 1777 /run/flora
ENTRYPOINT ["/usr/local/bin/eventlog-live-otelcol"]
