[tools]
yarn = '1.22.22'
node = '22.14.0'
ghcup = '0.1.40.0'

[env]
PATH = "{{env.HOME}}/.ghcup/bin:{{env.PATH}}"

[tasks.install-haskell-toolchain]
description = "Install the haskell toolchain"
run = ["ghcup install ghc 9.6.6 --set -f ",
       "ghcup install cabal 3.14.1.1 --set -f",
       ]

[tasks.install-migration-tool]
description = "Install postgresql-migration"
run = "cabal install postgresql-migration-0.2.1.8"

[tasks.db-migrate]
description = "Schema migrations"
depends = ['install-migration-tool']
run = "make db-init && make db-migrate && make db-provision"

[tasks.start-release]
description = "Start flora-server"
depends = ['db-migrate']
run = "make start-release"

[tasks.install-js-deps]
description = "Install JS dependencies"
run = "yarn install --immutable --immutable-cache --check-cache"
dir = "assets"

[tasks.build-js]
description = "Build JS assets"
depends = "install-js-deps"
run = ["node esbuild.config.js", "cp -rv css js icons ../static/"]
dir = "assets"
