[tools]
yarn = '1.22.22'
node = '22.14.0'
ghcup = '0.1.40.0'

[tasks.install-haskell-toolchain]
description = "Install the haskell toolchain"
run = ["ghcup install ghc 9.6.6 --set -f ",
       "ghcup install cabal 3.14.1.1 --set -f",
       "cabal update"
       ]

[tasks.install-js-deps]
description = "Install JS dependencies"
run = "yarn install --immutable --immutable-cache --check-cache"
dir = "assets"

[tasks.build-js]
description = "Build JS assets"
depends = "install-js-deps"
run = ["node esbuild.config.js", "cp -rv css js icons ../static/"]
dir = "assets"
