{
 "title": "Flora Eventlog Heap",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(ghc_eventlog_HeapSize_bytes,job)"
    }
   },
   { "name": "heap_prof_sample_limit", "label": "HeapProfSample Limit", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HeapSize for ${service_name}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(job) (ghc_eventlog_HeapSize_bytes{job=~\"$service_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage for ${service_name}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "service_name"
  },
  {
   "title": "HeapProfSample for ${service_name}",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ghc_eventlog_HeapProfSample_bytes{job=\"${service_name}\"}\nand\ntopk(\n  ${heap_prof_sample_limit},\n  sum_over_time(ghc_eventlog_HeapProfSample_bytes{job=\"${service_name}\"}[${__range}] @ ${__to:date:seconds})\n))\nor\nsum by(job) ((ghc_eventlog_HeapProfSample_bytes{job=\"${service_name}\"}\nunless\ntopk(\n  ${heap_prof_sample_limit},\n  sum_over_time(ghc_eventlog_HeapProfSample_bytes{job=\"${service_name}\"}[${__range}] @ ${__to:date:seconds})\n)))",
     "legendFormat": "{{heapProfLabel}}"
    }
   ]
  },
  {
   "title": "HeapSize for ${service_name}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(ghc_eventlog_HeapSize_bytes{job=\"$service_name\"})",
     "legendFormat": "HeapSize"
    },
    {
     "expr": "avg(ghc_eventlog_BlocksSize_bytes{job=\"$service_name\"})",
     "legendFormat": "BlocksSize"
    },
    {
     "expr": "avg(ghc_eventlog_HeapLive_bytes{job=\"$service_name\"})",
     "legendFormat": "HeapLive"
    }
   ]
  },
  {
   "title": "MemReturn for ${service_name}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mblock" } },
   "targets": [
    {
     "expr": "avg(ghc_eventlog_MemCurrent{job=\"$service_name\"})",
     "legendFormat": "MemCurrent"
    },
    {
     "expr": "avg(ghc_eventlog_MemNeeded{job=\"$service_name\"})",
     "legendFormat": "MemNeeded"
    },
    {
     "expr": "avg(ghc_eventlog_MemReturned{job=\"$service_name\"})",
     "legendFormat": "MemReturned"
    }
   ]
  },
  {
   "title": "HeapAllocated for ${service_name}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job) (delta(ghc_eventlog_HeapAllocated_bytes_total{job=\"$service_name\"}[$__interval]))",
     "legendFormat": "HeapAllocated"
    }
   ]
  }
 ]
}