upstream flora {
    server devel:8084;
}

server {
    listen      80;
    server_name localhost;

    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    location ~ /favicon.(ico|svg) {
        log_not_found off;
        access_log off;
        proxy_pass http://flora;
    }

    location = /robots.txt {
        log_not_found off;
        access_log off;
        proxy_pass http://flora;
    }

    location /metrics {
        deny all;
    }

    location /static {
        etag off;
        expires max;
        autoindex off;
        add_header Cache-Control public;
        gzip_static  on;
        proxy_pass http://flora;
    }

    location / {
        proxy_pass http://flora;
    }
}
