name: Database Index Checks

on:
  pull_request:
  push:
    branches: ["main", "development"]

concurrency:
  group: database-index-checks-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  generateMatrix:
    name: "Generate matrix from cabal"
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: kleidukos/get-tested@v0.1.9.1
        with:
          cabal-file: flora.cabal
          ubuntu-version: "24.04"
          version: 0.1.7.1

  database-index-checks:
    needs: generateMatrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.generateMatrix.outputs.matrix) }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v7

    - name: Set up Haskell
      id: setup-haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"

    - name: Configure environment
      run: |
        ./.github/workflows/setup.sh
        echo "$HOME/.ghcup/bin" >> $GITHUB_PATH
        echo "$HOME/.cabal/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/node_modules/.bin" >> $GITHUB_PATH
        touch ~/.pgpass
        chmod 0600 ~/.pgpass
        cabal update

    - name: Create freeze file
      run: cabal freeze --enable-tests

    - name: Cache
      uses: actions/cache@v5
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ hashFiles('./dist-newstyle/cache/plan.json') }}
        restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}-

    - name: Migrate
      run: |
        set -x
        cabal run -- flora-cli -c environment.ci.kdl create-db
        cabal run -- flora-migrate -c environment.ci.kdl
      env:
        PGPASSWORD: "postgres"

    - name: Check missing FK indexes
      run: .github/workflows/check-missing-fk-indexes.sh
      env:
        FLORA_DB_CONNSTRING: "postgresql://postgres:postgres@localhost/flora_test"

    - name: Check duplicate indexes
      run: .github/workflows/check-duplicate-indexes.sh
      env:
        FLORA_DB_CONNSTRING: "postgresql://postgres:postgres@localhost/flora_test"
