name: Publish Docker Image

on:
  push:
    branches: ["development"]
    paths:
      - Dockerfile
      - docker-compose.yml
      - scripts/.zshrc

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Create freeze file"
        run: |
          cabal freeze --enable-tests

      - name: Cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ hashFiles('./dist-newstyle/cache/plan.json') }}
          restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
               docker build . --tag ghcr.io/flora-pm/flora-server:latest
               docker run ghcr.io/flora-pm/flora-server:latest
               docker push ghcr.io/flora-pm/flora-server:latest

