name: Scan for vulnerabilities
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  haskell-security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: haskell-actions/setup@6037f33647c3f17758a2356c80fc4a53d7e0685d # v2.12.0
        with:
          ghc-version: '9.10.3'

      - name: Run Haskell Security Action
        uses: blackheaven/haskell-security-action@5b175efa1845a44cb6404a8dfd9a9cc65fcdb2ac # master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

