name: Build Docker Image

on:
  pull_request:
    branches: ["main", "development"]
    paths:
      - Dockerfile
      - docker-compose.yml
      - scripts/.zshrc

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build the Docker image
        run: make docker-build
