name: Build Docker Image

on:
  pull_request:
    branches: ["main", "development"]
    paths:
      - Dockerfile
      - docker-compose.yml
      - scripts/.zshrc

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - uses: actions/checkout@v6

      - name: Build the Docker image
        run: make docker-build
